package com.predial.repositorio;

import java.nio.charset.StandardCharsets;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.SecureRandom;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.KeySpec;

import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.PBEKeySpec;
import javax.crypto.spec.SecretKeySpec;

import com.google.common.hash.Hashing;

import jakarta.activation.DataHandler;
import jakarta.activation.DataSource;
import jakarta.activation.FileDataSource;
import jakarta.mail.Authenticator;
import jakarta.mail.BodyPart;
import jakarta.mail.Message;
import jakarta.mail.MessagingException;
import jakarta.mail.PasswordAuthentication;
import jakarta.mail.Session;
import jakarta.mail.Transport;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeBodyPart;
import jakarta.mail.internet.MimeMessage;
import jakarta.mail.internet.MimeMultipart;

public interface GeneradoresRepositorio {
	public default void sendMail(String to,String subject,String content,String[] imagenes){
		int i = 0 ;
	     final String username = "andresolmos2784@gmail.com";
	     final String password = "ikkwrbbdwuyywemv";
	       
	Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
	Matcher mather = pattern.matcher(to);
	if(mather.find() == true) { 
		Authenticator auth = new Authenticator() {
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(username, password);
				}
				};
	Properties prop = new Properties();
	prop.put("mail.smtp.host", "smtp.gmail.com");
	prop.put("mail.smtp.port", "465");
	prop.put("mail.smtp.auth", "true");
	prop.put("mail.smtp.socketFactory.port", "465");
	prop.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
	Session session = Session.getInstance(prop,auth);
	 
	        try {
	        Message message = new MimeMessage(session);
	        message.setFrom(new InternetAddress(username));
	        message.setRecipients(
	             Message.RecipientType.TO,
	             InternetAddress.parse(to)
	        );
	        message.setSubject(subject);
	        MimeMultipart multipart = new MimeMultipart("related");
	        
	        BodyPart messageBodyPart = new MimeBodyPart();
	        messageBodyPart.setContent(content, "text/html");
	        multipart.addBodyPart(messageBodyPart);
	        for(String urlImg: imagenes){
	        	messageBodyPart = new MimeBodyPart();
		        DataSource fdsa = new FileDataSource(urlImg);
		        
		        messageBodyPart.setDataHandler(new DataHandler(fdsa));
		        messageBodyPart.setHeader("Content-ID", "<image"+i+">");
		        
		        multipart.addBodyPart(messageBodyPart);
		        i++;
	        }

	           
	          
	        
	        message.setContent(multipart);
	        Transport.send(message);
	        System.out.println("enviado");
	        } catch (MessagingException e) {
	        e.printStackTrace();

	        }
	}else {
		System.out.println("no enviado");
	} 
	}
	
	

	
	public default String generarToken() {
		String token =  String.valueOf(((int) (Math.random() * 1000000)));
		return token;
	}
	
	public default String convertirSHA256(String text ,String salt) throws NoSuchProviderException, NoSuchAlgorithmException, InvalidKeySpecException, NoSuchPaddingException, InvalidKeyException, InvalidAlgorithmParameterException, IllegalBlockSizeException, BadPaddingException {
		System.out.println(text);
		String password = "fulano";
		SecretKeyFactory factory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256");
		KeySpec spec = new PBEKeySpec(password.toCharArray(), salt.getBytes(), 65536, 256);
	    SecretKey secret = new SecretKeySpec(factory.generateSecret(spec).getEncoded(), "AES");
	    
	    byte[] iv = new byte[16];
	    new SecureRandom().nextBytes(iv);
	    IvParameterSpec IvparameterSpec= new IvParameterSpec(iv);
	    
	    Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
	    cipher.init(Cipher.ENCRYPT_MODE, secret, IvparameterSpec);
	    byte[] cipherText = cipher.doFinal(text.getBytes());
	    System.out.println(cipherText);
	    
	    return Hashing.sha256().hashString(cipherText.toString(), StandardCharsets.UTF_8).toString();
	    
//	    return Base64.getEncoder()
//	        .encodeToString(cipherText);
}
	
	public default String emailContent(String token) {
		String hrml =  ""
				+ "<!DOCTYPE html>\r\n"
				+ "\r\n"
				+ "<html lang=\"en\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" xmlns:v=\"urn:schemas-microsoft-com:vml\">\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "	<title></title>\r\n"
				+ "	<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\" />\r\n"
				+ "	<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\" />\r\n"
				+ "	<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]-->\r\n"
				+ "	<style>\r\n"
				+ "		* {\r\n"
				+ "			box-sizing: border-box;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		body {\r\n"
				+ "			margin: 0;\r\n"
				+ "			padding: 0;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		a[x-apple-data-detectors] {\r\n"
				+ "			color: inherit !important;\r\n"
				+ "			text-decoration: inherit !important;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		#MessageViewBody a {\r\n"
				+ "			color: inherit;\r\n"
				+ "			text-decoration: none;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		p {\r\n"
				+ "			line-height: inherit\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		.desktop_hide,\r\n"
				+ "		.desktop_hide table {\r\n"
				+ "			mso-hide: all;\r\n"
				+ "			display: none;\r\n"
				+ "			max-height: 0px;\r\n"
				+ "			overflow: hidden;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		@media (max-width:660px) {\r\n"
				+ "\r\n"
				+ "			.desktop_hide table.icons-inner,\r\n"
				+ "			.social_block.desktop_hide .social-table {\r\n"
				+ "				display: inline-block !important;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.icons-inner {\r\n"
				+ "				text-align: center;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.icons-inner td {\r\n"
				+ "				margin: 0 auto;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.image_block img.big,\r\n"
				+ "			.row-content {\r\n"
				+ "				width: 100% !important;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.mobile_hide {\r\n"
				+ "				display: none;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.stack .column {\r\n"
				+ "				width: 100%;\r\n"
				+ "				display: block;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.mobile_hide {\r\n"
				+ "				min-height: 0;\r\n"
				+ "				max-height: 0;\r\n"
				+ "				max-width: 0;\r\n"
				+ "				overflow: hidden;\r\n"
				+ "				font-size: 0px;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.desktop_hide,\r\n"
				+ "			.desktop_hide table {\r\n"
				+ "				display: table !important;\r\n"
				+ "				max-height: none !important;\r\n"
				+ "			}\r\n"
				+ "		}\r\n"
				+ "	</style>\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body style=\"background-color: #f8f8f9; margin: 0; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;\">\r\n"
				+ "	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"nl-container\" role=\"presentation\"\r\n"
				+ "		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #f8f8f9;\" width=\"100%\">\r\n"
				+ "		<tbody>\r\n"
				+ "			<tr>\r\n"
				+ "				<td>\r\n"
				+ "					<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-1\"\r\n"
				+ "						role=\"presentation\"\r\n"
				+ "						style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #1aa19c;\" width=\"100%\">\r\n"
				+ "						<tbody>\r\n"
				+ "							<tr>\r\n"
				+ "								<td>\r\n"
				+ "									<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "										class=\"row-content stack\" role=\"presentation\"\r\n"
				+ "										style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #1aa19c; color: #000000; width: 640px;\"\r\n"
				+ "										width=\"640\">\r\n"
				+ "										<tbody>\r\n"
				+ "											<tr>\r\n"
				+ "												<td class=\"column column-1\"\r\n"
				+ "													style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\"\r\n"
				+ "													width=\"100%\">\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"divider_block block-1\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\">\r\n"
				+ "																<div align=\"center\" class=\"alignment\">\r\n"
				+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "																		role=\"presentation\"\r\n"
				+ "																		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "																		width=\"100%\">\r\n"
				+ "																		<tr>\r\n"
				+ "																			<td class=\"divider_inner\"\r\n"
				+ "																				style=\"font-size: 1px; line-height: 1px; border-top: 4px solid #1AA19C;\">\r\n"
				+ "																				<span> </span></td>\r\n"
				+ "																		</tr>\r\n"
				+ "																	</table>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "												</td>\r\n"
				+ "											</tr>\r\n"
				+ "										</tbody>\r\n"
				+ "									</table>\r\n"
				+ "								</td>\r\n"
				+ "							</tr>\r\n"
				+ "						</tbody>\r\n"
				+ "					</table>\r\n"
				+ "					<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-2\"\r\n"
				+ "						role=\"presentation\"\r\n"
				+ "						style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #fff;\" width=\"100%\">\r\n"
				+ "						<tbody>\r\n"
				+ "							<tr>\r\n"
				+ "								<td>\r\n"
				+ "									<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "										class=\"row-content stack\" role=\"presentation\"\r\n"
				+ "										style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #fff; color: #000000; width: 640px;\"\r\n"
				+ "										width=\"640\">\r\n"
				+ "										<tbody>\r\n"
				+ "											<tr>\r\n"
				+ "												<td class=\"column column-1\"\r\n"
				+ "													style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\"\r\n"
				+ "													width=\"100%\">\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"image_block block-1\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\"\r\n"
				+ "																style=\"padding-bottom:25px;padding-top:22px;width:100%;padding-right:0px;padding-left:0px;\">\r\n"
				+ "																<div align=\"center\" class=\"alignment\"\r\n"
				+ "																	style=\"line-height:10px\"><img alt=\"I'm an image\"\r\n"
				+ "																		src=\"cid:image0\"\r\n"
				+ "																		style=\"display: block; height: auto; border: 0; width: 160px; max-width: 100%;\"\r\n"
				+ "																		title=\"I'm an image\" width=\"160\" /></div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "												</td>\r\n"
				+ "											</tr>\r\n"
				+ "										</tbody>\r\n"
				+ "									</table>\r\n"
				+ "								</td>\r\n"
				+ "							</tr>\r\n"
				+ "						</tbody>\r\n"
				+ "					</table>\r\n"
				+ "					<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-3\"\r\n"
				+ "						role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "						<tbody>\r\n"
				+ "							<tr>\r\n"
				+ "								<td>\r\n"
				+ "									<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "										class=\"row-content stack\" role=\"presentation\"\r\n"
				+ "										style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #f8f8f9; color: #000000; width: 640px;\"\r\n"
				+ "										width=\"640\">\r\n"
				+ "										<tbody>\r\n"
				+ "											<tr>\r\n"
				+ "												<td class=\"column column-1\"\r\n"
				+ "													style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 5px; padding-bottom: 5px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\"\r\n"
				+ "													width=\"100%\">\r\n"
				+ "													<table border=\"0\" cellpadding=\"20\" cellspacing=\"0\"\r\n"
				+ "														class=\"divider_block block-1\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\">\r\n"
				+ "																<div align=\"center\" class=\"alignment\">\r\n"
				+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "																		role=\"presentation\"\r\n"
				+ "																		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "																		width=\"100%\">\r\n"
				+ "																		<tr>\r\n"
				+ "																			<td class=\"divider_inner\"\r\n"
				+ "																				style=\"font-size: 1px; line-height: 1px; border-top: 0px solid #BBBBBB;\">\r\n"
				+ "																				<span> </span></td>\r\n"
				+ "																		</tr>\r\n"
				+ "																	</table>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "												</td>\r\n"
				+ "											</tr>\r\n"
				+ "										</tbody>\r\n"
				+ "									</table>\r\n"
				+ "								</td>\r\n"
				+ "							</tr>\r\n"
				+ "						</tbody>\r\n"
				+ "					</table>\r\n"
				+ "					<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-4\"\r\n"
				+ "						role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "						<tbody>\r\n"
				+ "							<tr>\r\n"
				+ "								<td>\r\n"
				+ "									<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "										class=\"row-content stack\" role=\"presentation\"\r\n"
				+ "										style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #fff; color: #000000; width: 640px;\"\r\n"
				+ "										width=\"640\">\r\n"
				+ "										<tbody>\r\n"
				+ "											<tr>\r\n"
				+ "												<td class=\"column column-1\"\r\n"
				+ "													style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\"\r\n"
				+ "													width=\"100%\">\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"divider_block block-1\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\"\r\n"
				+ "																style=\"padding-bottom:12px;padding-top:60px;\">\r\n"
				+ "																<div align=\"center\" class=\"alignment\">\r\n"
				+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "																		role=\"presentation\"\r\n"
				+ "																		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "																		width=\"100%\">\r\n"
				+ "																		<tr>\r\n"
				+ "																			<td class=\"divider_inner\"\r\n"
				+ "																				style=\"font-size: 1px; line-height: 1px; border-top: 0px solid #BBBBBB;\">\r\n"
				+ "																				<span> </span></td>\r\n"
				+ "																		</tr>\r\n"
				+ "																	</table>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"image_block block-2\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\"\r\n"
				+ "																style=\"padding-left:40px;padding-right:40px;width:100%;\">\r\n"
				+ "																<div align=\"center\" class=\"alignment\"\r\n"
				+ "																	style=\"line-height:10px\"><img alt=\"I'm an image\"\r\n"
				+ "																		class=\"big\" src=\"cid:image0\"\r\n"
				+ "																		style=\"display: block; height: auto; border: 0; width: 352px; max-width: 100%;\"\r\n"
				+ "																		title=\"I'm an image\" width=\"352\" /></div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"divider_block block-3\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\" style=\"padding-top:50px;\">\r\n"
				+ "																<div align=\"center\" class=\"alignment\">\r\n"
				+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "																		role=\"presentation\"\r\n"
				+ "																		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "																		width=\"100%\">\r\n"
				+ "																		<tr>\r\n"
				+ "																			<td class=\"divider_inner\"\r\n"
				+ "																				style=\"font-size: 1px; line-height: 1px; border-top: 0px solid #BBBBBB;\">\r\n"
				+ "																				<span> </span></td>\r\n"
				+ "																		</tr>\r\n"
				+ "																	</table>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"text_block block-4\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\"\r\n"
				+ "																style=\"padding-bottom:10px;padding-left:40px;padding-right:40px;padding-top:10px;\">\r\n"
				+ "																<div style=\"font-family: sans-serif\">\r\n"
				+ "																	<div class=\"\"\r\n"
				+ "																		style=\"font-size: 12px; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;\">\r\n"
				+ "																		<p\r\n"
				+ "																			style=\"margin: 0; font-size: 16px; text-align: center; mso-line-height-alt: 19.2px;\">\r\n"
				+ "																			<span\r\n"
				+ "																				style=\"font-size:30px;color:#2b303a;\"><strong\r\n"
				+ "																					style=\"color:#2b303a;font-family:inherit;font-family:inherit;font-size:30px;\">token\r\n"
				+ "																					de </strong></span><span\r\n"
				+ "																				style=\"text-align:left;background-color:transparent;font-size:30px;\"><span\r\n"
				+ "																					style=\"color:#2b303a;\"><strong>modificación</strong></span></span>\r\n"
				+ "																		</p>\r\n"
				+ "																	</div>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"text_block block-5\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\"\r\n"
				+ "																style=\"padding-bottom:10px;padding-left:40px;padding-right:40px;padding-top:10px;\">\r\n"
				+ "																<div style=\"font-family: sans-serif\">\r\n"
				+ "																	<div class=\"\"\r\n"
				+ "																		style=\"font-size: 12px; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 18px; color: #555555; line-height: 1.5;\">\r\n"
				+ "																		<p\r\n"
				+ "																			style=\"margin: 0; mso-line-height-alt: 18px;\">\r\n"
				+ "																			Este token le servirá para modificar las\r\n"
				+ "																			tarifas y los avalúos en el aplicativo Sinfa\r\n"
				+ "																			Predial</p>\r\n"
				+ "																		<p\r\n"
				+ "																			style=\"margin: 0; mso-line-height-alt: 18px;\">\r\n"
				+ "																			por favor introduzca este token en la zona\r\n"
				+ "																			requerida por el aplicativo</p>\r\n"
				+ "																	</div>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"divider_block block-6\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\" style=\"padding-top:50px;\">\r\n"
				+ "																<div align=\"center\" class=\"alignment\">\r\n"
				+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "																		role=\"presentation\"\r\n"
				+ "																		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "																		width=\"100%\">\r\n"
				+ "																		<tr>\r\n"
				+ "																			<td class=\"divider_inner\"\r\n"
				+ "																				style=\"font-size: 1px; line-height: 1px; border-top: 0px solid #BBBBBB;\">\r\n"
				+ "																				<span> </span></td>\r\n"
				+ "																		</tr>\r\n"
				+ "																	</table>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "												</td>\r\n"
				+ "											</tr>\r\n"
				+ "										</tbody>\r\n"
				+ "									</table>\r\n"
				+ "								</td>\r\n"
				+ "							</tr>\r\n"
				+ "						</tbody>\r\n"
				+ "					</table>\r\n"
				+ "					<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-5\"\r\n"
				+ "						role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "						<tbody>\r\n"
				+ "							<tr>\r\n"
				+ "								<td>\r\n"
				+ "									<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "										class=\"row-content stack\" role=\"presentation\"\r\n"
				+ "										style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #f3fafa; color: #000000; width: 640px;\"\r\n"
				+ "										width=\"640\">\r\n"
				+ "										<tbody>\r\n"
				+ "											<tr>\r\n"
				+ "												<td class=\"column column-1\"\r\n"
				+ "													style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; border-left: 30px solid #FFFFFF; border-right: 30px solid #FFFFFF; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-bottom: 0px;\"\r\n"
				+ "													width=\"100%\">\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"divider_block block-1\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\">\r\n"
				+ "																<div align=\"center\" class=\"alignment\">\r\n"
				+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "																		role=\"presentation\"\r\n"
				+ "																		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "																		width=\"100%\">\r\n"
				+ "																		<tr>\r\n"
				+ "																			<td class=\"divider_inner\"\r\n"
				+ "																				style=\"font-size: 1px; line-height: 1px; border-top: 4px solid #1AA19C;\">\r\n"
				+ "																				<span> </span></td>\r\n"
				+ "																		</tr>\r\n"
				+ "																	</table>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"divider_block block-2\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\" style=\"padding-top:25px;\">\r\n"
				+ "																<div align=\"center\" class=\"alignment\">\r\n"
				+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "																		role=\"presentation\"\r\n"
				+ "																		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "																		width=\"100%\">\r\n"
				+ "																		<tr>\r\n"
				+ "																			<td class=\"divider_inner\"\r\n"
				+ "																				style=\"font-size: 1px; line-height: 1px; border-top: 0px solid #BBBBBB;\">\r\n"
				+ "																				<span> </span></td>\r\n"
				+ "																		</tr>\r\n"
				+ "																	</table>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"text_block block-3\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\"\r\n"
				+ "																style=\"padding-bottom:5px;padding-left:10px;padding-right:10px;padding-top:10px;\">\r\n"
				+ "																<div style=\"font-family: sans-serif\">\r\n"
				+ "																	<div class=\"\"\r\n"
				+ "																		style=\"font-size: 12px; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;\">\r\n"
				+ "																		<p\r\n"
				+ "																			style=\"margin: 0; font-size: 16px; text-align: center; mso-line-height-alt: 19.2px;\">\r\n"
				+ "																			Su token de modificación es:</p>\r\n"
				+ "																	</div>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"text_block block-4\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\" style=\"padding-bottom:32px;\">\r\n"
				+ "																<div style=\"font-family: sans-serif\">\r\n"
				+ "																	<div class=\"\"\r\n"
				+ "																		style=\"font-size: 12px; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 14.399999999999999px; color: #555555; line-height: 1.2;\">\r\n"
				+ "																		<p\r\n"
				+ "																			style=\"margin: 0; font-size: 16px; text-align: center; mso-line-height-alt: 19.2px;\">\r\n"
				+ "																			<span\r\n"
				+ "																				style=\"color:#1aa19c;font-size:38px;\"><span\r\n"
				+ "																					style=\"\"><strong>"+token+"</strong></span></span>\r\n"
				+ "																		</p>\r\n"
				+ "																	</div>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "												</td>\r\n"
				+ "											</tr>\r\n"
				+ "										</tbody>\r\n"
				+ "									</table>\r\n"
				+ "								</td>\r\n"
				+ "							</tr>\r\n"
				+ "						</tbody>\r\n"
				+ "					</table>\r\n"
				+ "					<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-6\"\r\n"
				+ "						role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "						<tbody>\r\n"
				+ "							<tr>\r\n"
				+ "								<td>\r\n"
				+ "									<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "										class=\"row-content stack\" role=\"presentation\"\r\n"
				+ "										style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #fff; color: #000000; border-radius: 0; width: 640px;\"\r\n"
				+ "										width=\"640\">\r\n"
				+ "										<tbody>\r\n"
				+ "											<tr>\r\n"
				+ "												<td class=\"column column-1\"\r\n"
				+ "													style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\"\r\n"
				+ "													width=\"100%\">\r\n"
				+ "													<table border=\"0\" cellpadding=\"10\" cellspacing=\"0\"\r\n"
				+ "														class=\"divider_block block-1\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\">\r\n"
				+ "																<div align=\"center\" class=\"alignment\">\r\n"
				+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "																		role=\"presentation\"\r\n"
				+ "																		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "																		width=\"100%\">\r\n"
				+ "																		<tr>\r\n"
				+ "																			<td class=\"divider_inner\"\r\n"
				+ "																				style=\"font-size: 1px; line-height: 1px; border-top: 1px solid #BBBBBB;\">\r\n"
				+ "																				<span> </span></td>\r\n"
				+ "																		</tr>\r\n"
				+ "																	</table>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "												</td>\r\n"
				+ "											</tr>\r\n"
				+ "										</tbody>\r\n"
				+ "									</table>\r\n"
				+ "								</td>\r\n"
				+ "							</tr>\r\n"
				+ "						</tbody>\r\n"
				+ "					</table>\r\n"
				+ "					<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-7\"\r\n"
				+ "						role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "						<tbody>\r\n"
				+ "							<tr>\r\n"
				+ "								<td>\r\n"
				+ "									<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "										class=\"row-content stack\" role=\"presentation\"\r\n"
				+ "										style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #2b303a; color: #000000; width: 640px;\"\r\n"
				+ "										width=\"640\">\r\n"
				+ "										<tbody>\r\n"
				+ "											<tr>\r\n"
				+ "												<td class=\"column column-1\"\r\n"
				+ "													style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\"\r\n"
				+ "													width=\"100%\">\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"divider_block block-1\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\">\r\n"
				+ "																<div align=\"center\" class=\"alignment\">\r\n"
				+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "																		role=\"presentation\"\r\n"
				+ "																		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "																		width=\"100%\">\r\n"
				+ "																		<tr>\r\n"
				+ "																			<td class=\"divider_inner\"\r\n"
				+ "																				style=\"font-size: 1px; line-height: 1px; border-top: 4px solid #1AA19C;\">\r\n"
				+ "																				<span> </span></td>\r\n"
				+ "																		</tr>\r\n"
				+ "																	</table>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"social_block block-2\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\"\r\n"
				+ "																style=\"padding-bottom:10px;padding-left:10px;padding-right:10px;padding-top:28px;text-align:center;\">\r\n"
				+ "																<div align=\"center\" class=\"alignment\">\r\n"
				+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "																		class=\"social-table\" role=\"presentation\"\r\n"
				+ "																		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block;\"\r\n"
				+ "																		width=\"208px\">\r\n"
				+ "																		<tr>\r\n"
				+ "																			<td style=\"padding:0 10px 0 10px;\"><a\r\n"
				+ "																					href=\"https://www.facebook.com/\"\r\n"
				+ "																					target=\"_blank\"><img alt=\"Facebook\"\r\n"
				+ "																						height=\"32\"\r\n"
				+ "																						src=\"cid:image1\"\r\n"
				+ "																						style=\"display: block; height: auto; border: 0;\"\r\n"
				+ "																						title=\"Facebook\"\r\n"
				+ "																						width=\"32\" /></a></td>\r\n"
				+ "																			<td style=\"padding:0 10px 0 10px;\"><a\r\n"
				+ "																					href=\"https://twitter.com/\"\r\n"
				+ "																					target=\"_blank\"><img alt=\"Twitter\"\r\n"
				+ "																						height=\"32\"\r\n"
				+ "																						src=\"cid:image2\"\r\n"
				+ "																						style=\"display: block; height: auto; border: 0;\"\r\n"
				+ "																						title=\"Twitter\"\r\n"
				+ "																						width=\"32\" /></a></td>\r\n"
				+ "																			<td style=\"padding:0 10px 0 10px;\"><a\r\n"
				+ "																					href=\"https://instagram.com/\"\r\n"
				+ "																					target=\"_blank\"><img alt=\"Instagram\"\r\n"
				+ "																						height=\"32\"\r\n"
				+ "																						src=\"cid:image3\"\r\n"
				+ "																						style=\"display: block; height: auto; border: 0;\"\r\n"
				+ "																						title=\"Instagram\"\r\n"
				+ "																						width=\"32\" /></a></td>\r\n"
				+ "																			<td style=\"padding:0 10px 0 10px;\"><a\r\n"
				+ "																					href=\"https://www.linkedin.com/\"\r\n"
				+ "																					target=\"_blank\"><img alt=\"LinkedIn\"\r\n"
				+ "																						height=\"32\"\r\n"
				+ "																						src=\"cid:image4\"\r\n"
				+ "																						style=\"display: block; height: auto; border: 0;\"\r\n"
				+ "																						title=\"LinkedIn\"\r\n"
				+ "																						width=\"32\" /></a></td>\r\n"
				+ "																		</tr>\r\n"
				+ "																	</table>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"text_block block-3\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\"\r\n"
				+ "																style=\"padding-bottom:10px;padding-left:40px;padding-right:40px;padding-top:15px;\">\r\n"
				+ "																<div style=\"font-family: sans-serif\">\r\n"
				+ "																	<div class=\"\"\r\n"
				+ "																		style=\"font-size: 12px; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; mso-line-height-alt: 18px; color: #555555; line-height: 1.5;\">\r\n"
				+ "																		<p\r\n"
				+ "																			style=\"margin: 0; font-size: 14px; text-align: left; mso-line-height-alt: 19.5px;\">\r\n"
				+ "																			<span\r\n"
				+ "																				style=\"color:#ffffff;font-size:13px;\">Recuerde\r\n"
				+ "																				que en Sinfa estamos para ayudarlo, si\r\n"
				+ "																				tiene problemas por favor comuníquese a\r\n"
				+ "																				los siguientes medios</span></p>\r\n"
				+ "																		<p\r\n"
				+ "																			style=\"margin: 0; mso-line-height-alt: 19.5px;\">\r\n"
				+ "																			<span style=\"color:#ffffff;\">Telefono:\r\n"
				+ "																				3994567894</span></p>\r\n"
				+ "																		<p\r\n"
				+ "																			style=\"margin: 0; mso-line-height-alt: 19.5px;\">\r\n"
				+ "																			<span style=\"color:#ffffff;\">Correo: <a\r\n"
				+ "																					href=\"mailto:soportex@sinfa.com.co\"\r\n"
				+ "																					rel=\"noopener\"\r\n"
				+ "																					style=\"text-decoration:underline;color:#ffffff;\"\r\n"
				+ "																					target=\"_blank\">soportex@sinfa.com.co</a></span>\r\n"
				+ "																		</p>\r\n"
				+ "																	</div>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"divider_block block-4\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\"\r\n"
				+ "																style=\"padding-bottom:10px;padding-left:40px;padding-right:40px;padding-top:25px;\">\r\n"
				+ "																<div align=\"center\" class=\"alignment\">\r\n"
				+ "																	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "																		role=\"presentation\"\r\n"
				+ "																		style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "																		width=\"100%\">\r\n"
				+ "																		<tr>\r\n"
				+ "																			<td class=\"divider_inner\"\r\n"
				+ "																				style=\"font-size: 1px; line-height: 1px; border-top: 1px solid #555961;\">\r\n"
				+ "																				<span> </span></td>\r\n"
				+ "																		</tr>\r\n"
				+ "																	</table>\r\n"
				+ "																</div>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "												</td>\r\n"
				+ "											</tr>\r\n"
				+ "										</tbody>\r\n"
				+ "									</table>\r\n"
				+ "								</td>\r\n"
				+ "							</tr>\r\n"
				+ "						</tbody>\r\n"
				+ "					</table>\r\n"
				+ "					<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-8\"\r\n"
				+ "						role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "						<tbody>\r\n"
				+ "							<tr>\r\n"
				+ "								<td>\r\n"
				+ "									<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "										class=\"row-content stack\" role=\"presentation\"\r\n"
				+ "										style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 640px;\"\r\n"
				+ "										width=\"640\">\r\n"
				+ "										<tbody>\r\n"
				+ "											<tr>\r\n"
				+ "												<td class=\"column column-1\"\r\n"
				+ "													style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 5px; padding-bottom: 5px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\"\r\n"
				+ "													width=\"100%\">\r\n"
				+ "													<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "														class=\"icons_block block-1\" role=\"presentation\"\r\n"
				+ "														style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "														width=\"100%\">\r\n"
				+ "														<tr>\r\n"
				+ "															<td class=\"pad\"\r\n"
				+ "																style=\"vertical-align: middle; color: #9d9d9d; font-family: inherit; font-size: 15px; padding-bottom: 5px; padding-top: 5px; text-align: center;\">\r\n"
				+ "																<table cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "																	role=\"presentation\"\r\n"
				+ "																	style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
				+ "																	width=\"100%\">\r\n"
				+ "																	<tr>\r\n"
				+ "																		<td class=\"alignment\"\r\n"
				+ "																			style=\"vertical-align: middle; text-align: center;\">\r\n"
				+ "																			<!--[if vml]><table align=\"left\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;\"><![endif]-->\r\n"
				+ "																			<!--[if !vml]><!-->\r\n"
				+ "																			<table cellpadding=\"0\" cellspacing=\"0\"\r\n"
				+ "																				class=\"icons-inner\" role=\"presentation\"\r\n"
				+ "																				style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block; margin-right: -4px; padding-left: 0px; padding-right: 0px;\">\r\n"
				+ "																				<!--<![endif]-->\r\n"
				+ "																				<tr>\r\n"
				+ "																					<td\r\n"
				+ "																						style=\"vertical-align: middle; text-align: center; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 6px;\">\r\n"
				+ "																						<a href=\"https://www.designedwithbee.com/\"\r\n"
				+ "																							style=\"text-decoration: none;\"\r\n"
				+ "																							target=\"_blank\"><img\r\n"
				+ "																								align=\"center\"\r\n"
				+ "																								alt=\"Designed with BEE\"\r\n"
				+ "																								class=\"icon\" height=\"32\"\r\n"
				+ "																								src=\"cid:image5\"\r\n"
				+ "																								style=\"display: block; height: auto; margin: 0 auto; border: 0;\"\r\n"
				+ "																								width=\"34\" /></a></td>\r\n"
				+ "																					<td\r\n"
				+ "																						style=\"font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; font-size: 15px; color: #9d9d9d; vertical-align: middle; letter-spacing: undefined; text-align: center;\">\r\n"
				+ "																						<a href=\"https://www.designedwithbee.com/\"\r\n"
				+ "																							style=\"color: #9d9d9d; text-decoration: none;\"\r\n"
				+ "																							target=\"_blank\">Designed\r\n"
				+ "																							with BEE</a></td>\r\n"
				+ "																				</tr>\r\n"
				+ "																			</table>\r\n"
				+ "																		</td>\r\n"
				+ "																	</tr>\r\n"
				+ "																</table>\r\n"
				+ "															</td>\r\n"
				+ "														</tr>\r\n"
				+ "													</table>\r\n"
				+ "												</td>\r\n"
				+ "											</tr>\r\n"
				+ "										</tbody>\r\n"
				+ "									</table>\r\n"
				+ "								</td>\r\n"
				+ "							</tr>\r\n"
				+ "						</tbody>\r\n"
				+ "					</table>\r\n"
				+ "				</td>\r\n"
				+ "			</tr>\r\n"
				+ "		</tbody>\r\n"
				+ "	</table><!-- End -->\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>";
		return hrml;
	}
}
